"""
Pydantic schemas for Insight Forge API.
All DTOs match the Java versions exactly for API compatibility.
"""
from app.schemas.code_generation import (
    CombinedCodeResponse,
    CqlMetadataResponse,
    CqlResponse,
    SqlMetadataResponse,
    SqlPreviewRequest,
    SqlResponse,
)
from app.schemas.component import (
    ApproveComponentRequest,
    CodeDto,
    CodeRequest,
    ComplexityDto,
    ComponentDto,
    ComponentReferenceDto,
    ComponentReferenceRequest,
    ComponentStatsDto,
    ComponentSummaryDto,
    CreateAtomicComponentRequest,
    CreateCompositeComponentRequest,
    CreateVersionRequest,
    MetadataDto,
    SetCategoryRequest,
    TimingDto,
    TimingRequest,
    UpdateComponentRequest,
    UsageDto,
    ValueSetDto,
    ValueSetRequest,
    VersionHistoryEntryDto,
    VersionInfoDto,
)
from app.schemas.import_schema import ImportRequest, ImportResultDto
from app.schemas.llm import LlmRequest, LlmResponseDto
from app.schemas.measure import (
    CorrectionDto,
    CreateMeasureRequest,
    DataElementDto,
    GlobalConstraintsDto,
    GlobalConstraintsRequest,
    LogicalClauseDto,
    MeasureDto,
    MeasureSummaryDto,
    MeasureValueSetDto,
    PopulationDto,
    ThresholdDto,
    UpdateMeasureRequest,
    ValueSetCodeDto,
    ValueSetRefDto,
)
from app.schemas.test_patient import (
    CreateTestPatientRequest,
    FhirTestPatientDetailDto,
    FhirTestPatientSummaryDto,
    UpdateTestPatientRequest,
)
from app.schemas.validation import (
    ClassifierFeedbackRequest,
    ClassifierFeedbackStatsDto,
    PopulationResultDto,
    PreCheckResultDto,
    ValidationFactDto,
    ValidationNodeDto,
    ValidationTraceDto,
)

__all__ = [
    # Measure schemas
    "CorrectionDto",
    "CreateMeasureRequest",
    "DataElementDto",
    "GlobalConstraintsDto",
    "GlobalConstraintsRequest",
    "LogicalClauseDto",
    "MeasureDto",
    "MeasureSummaryDto",
    "MeasureValueSetDto",
    "PopulationDto",
    "ThresholdDto",
    "UpdateMeasureRequest",
    "ValueSetCodeDto",
    "ValueSetRefDto",
    # Component schemas
    "ApproveComponentRequest",
    "CodeDto",
    "CodeRequest",
    "ComplexityDto",
    "ComponentDto",
    "ComponentReferenceDto",
    "ComponentReferenceRequest",
    "ComponentStatsDto",
    "ComponentSummaryDto",
    "CreateAtomicComponentRequest",
    "CreateCompositeComponentRequest",
    "CreateVersionRequest",
    "MetadataDto",
    "SetCategoryRequest",
    "TimingDto",
    "TimingRequest",
    "UpdateComponentRequest",
    "UsageDto",
    "ValueSetDto",
    "ValueSetRequest",
    "VersionHistoryEntryDto",
    "VersionInfoDto",
    # Import schemas
    "ImportRequest",
    "ImportResultDto",
    # Code generation schemas
    "CombinedCodeResponse",
    "CqlMetadataResponse",
    "CqlResponse",
    "SqlMetadataResponse",
    "SqlPreviewRequest",
    "SqlResponse",
    # LLM schemas
    "LlmRequest",
    "LlmResponseDto",
    # Validation schemas
    "ClassifierFeedbackRequest",
    "ClassifierFeedbackStatsDto",
    "PopulationResultDto",
    "PreCheckResultDto",
    "ValidationFactDto",
    "ValidationNodeDto",
    "ValidationTraceDto",
    # Test patient schemas
    "CreateTestPatientRequest",
    "FhirTestPatientDetailDto",
    "FhirTestPatientSummaryDto",
    "UpdateTestPatientRequest",
]
